<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VoucherType;

class VoucherTypeSeeder extends Seeder
{
    public static function seedForTenant($tenantId)
    {
        // Check if voucher types already exist for this tenant
        $existingTypes = VoucherType::where('tenant_id', $tenantId)->count();
        if ($existingTypes > 0) {
            return; // Skip seeding if types already exist
        }

    $defaultVoucherTypes = [
            [
                'name' => 'Journal',
                'code' => 'JV',
                'abbreviation' => 'J',
                'description' => 'General journal entries for adjustments and corrections',
                'numbering_method' => 'auto',
                'prefix' => 'JV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'inventory_effect' => 'none',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Payment',
                'code' => 'PV',
                'abbreviation' => 'P',
                'description' => 'Payment vouchers for cash and bank payments',
                'numbering_method' => 'auto',
                'prefix' => 'PV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Receipt',
                'code' => 'RV',
                'abbreviation' => 'R',
                'description' => 'Receipt vouchers for cash and bank receipts',
                'numbering_method' => 'auto',
                'prefix' => 'RV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
              [
                'name' => 'Sales',
                'code' => 'SV',
                'abbreviation' => 'S',
                'description' => 'Sales vouchers for recording sales transactions',
                'numbering_method' => 'auto',
                'prefix' => 'SV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => true,
                'inventory_effect' => 'decrease',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Purchase',
                'code' => 'PUR',
                'abbreviation' => 'PU',
                'description' => 'Purchase vouchers for recording purchase transactions',
                'numbering_method' => 'auto',
                'prefix' => 'PUR-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => true,
                'inventory_effect' => 'increase',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Contra',
                'code' => 'CV',
                'abbreviation' => 'C',
                'description' => 'Contra vouchers for bank to cash or cash to bank transfers',
                'numbering_method' => 'auto',
                'prefix' => 'CV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            // --- Added Vouchers ---
            [
                'name' => 'Credit Note',
                'code' => 'CN',
                'abbreviation' => 'CN',
                'description' => 'Credit note for sales returns or downward adjustment of customer invoices',
                'numbering_method' => 'auto',
                'prefix' => 'CN-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => false,
                'inventory_effect' => 'none',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Debit Note',
                'code' => 'DN',
                'abbreviation' => 'DN',
                'description' => 'Debit note for purchase returns or downward adjustment of supplier bills',
                'numbering_method' => 'auto',
                'prefix' => 'DN-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => false,
                'inventory_effect' => 'none',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Sales Return',
                'code' => 'SR',
                'abbreviation' => 'SR',
                'description' => 'Sales return voucher (if separate from credit note)',
                'numbering_method' => 'auto',
                'prefix' => 'SR-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => true,
                'inventory_effect' => 'increase',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Purchase Return',
                'code' => 'PR',
                'abbreviation' => 'PR',
                'description' => 'Purchase return voucher (if separate from debit note)',
                'numbering_method' => 'auto',
                'prefix' => 'PR-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => true,
                'affects_inventory' => true,
                'inventory_effect' => 'decrease',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Material Issue',
                'code' => 'MI',
                'abbreviation' => 'MI',
                'description' => 'Material issue voucher for raw material issued to production',
                'numbering_method' => 'auto',
                'prefix' => 'MI-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => true,
                'inventory_effect' => 'decrease',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Material Receipt',
                'code' => 'MR',
                'abbreviation' => 'MR',
                'description' => 'Material receipt voucher for finished goods received from production',
                'numbering_method' => 'auto',
                'prefix' => 'MR-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => true,
                'inventory_effect' => 'increase',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Stock Transfer',
                'code' => 'ST',
                'abbreviation' => 'ST',
                'description' => 'Stock transfer voucher for movement of stock between warehouses/branches',
                'numbering_method' => 'auto',
                'prefix' => 'ST-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => true,
                'inventory_effect' => 'none',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Consumption',
                'code' => 'CON',
                'abbreviation' => 'CON',
                'description' => 'Consumption voucher for usage/consumption of raw materials',
                'numbering_method' => 'auto',
                'prefix' => 'CON-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => true,
                'inventory_effect' => 'decrease',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Production',
                'code' => 'PROD',
                'abbreviation' => 'PROD',
                'description' => 'Production/job work voucher for manufacturing/assembly process',
                'numbering_method' => 'auto',
                'prefix' => 'PROD-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => true,
                'inventory_effect' => 'increase',
                'affects_cashbank' => false,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Salary',
                'code' => 'SAL',
                'abbreviation' => 'SAL',
                'description' => 'Salary voucher for monthly salary posting',
                'numbering_method' => 'auto',
                'prefix' => 'SAL-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Overtime/Allowance',
                'code' => 'OT',
                'abbreviation' => 'OT',
                'description' => 'Overtime/allowance voucher for extra payments to staff',
                'numbering_method' => 'auto',
                'prefix' => 'OT-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Employee Advance',
                'code' => 'ADV',
                'abbreviation' => 'ADV',
                'description' => 'Employee advance voucher for advance paid to employees (IOU)',
                'numbering_method' => 'auto',
                'prefix' => 'ADV-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Reimbursement',
                'code' => 'REIM',
                'abbreviation' => 'REIM',
                'description' => 'Reimbursement voucher for staff expenses reimbursed',
                'numbering_method' => 'auto',
                'prefix' => 'REIM-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Petty Cash',
                'code' => 'PC',
                'abbreviation' => 'PC',
                'description' => 'Petty cash voucher for small day-to-day expenses',
                'numbering_method' => 'auto',
                'prefix' => 'PC-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Expense',
                'code' => 'EXP',
                'abbreviation' => 'EXP',
                'description' => 'Expense voucher for general business expenses',
                'numbering_method' => 'auto',
                'prefix' => 'EXP-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Prepaid Expense',
                'code' => 'PRE',
                'abbreviation' => 'PRE',
                'description' => 'Prepaid expense voucher for prepaid rent, insurance, etc.',
                'numbering_method' => 'auto',
                'prefix' => 'PRE-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Bank Charges',
                'code' => 'BC',
                'abbreviation' => 'BC',
                'description' => 'Bank charges voucher for bank fees and service charges',
                'numbering_method' => 'auto',
                'prefix' => 'BC-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Loan/Interest',
                'code' => 'LN',
                'abbreviation' => 'LN',
                'description' => 'Loan/interest voucher for loan repayment and interest',
                'numbering_method' => 'auto',
                'prefix' => 'LN-',
                'starting_number' => 1,
                'current_number' => 0,
                'has_reference' => false,
                'affects_inventory' => false,
                'affects_cashbank' => true,
                'is_system_defined' => true,
                'is_active' => true,
            ],
        ];

        foreach ($defaultVoucherTypes as $voucherType) {
            $voucherType['tenant_id'] = $tenantId;
            $voucherType['created_at'] = now();
            $voucherType['updated_at'] = now();

            VoucherType::create($voucherType);
        }
    }

    public function run()
    {
        // This method can be used for standalone seeding if needed
        $tenantId = $this->command->option('tenant-id');

        if ($tenantId) {
            self::seedForTenant($tenantId);
            $this->command->info("Voucher types seeded for tenant ID: {$tenantId}");
        } else {
            $this->command->error('Please provide --tenant-id option');
        }
    }
}
